development:
  mailgun_smtp_login: "postmaster@mailgun.eebulle.ch"
  mailgun_default_pswd: "74bcddfd59e3bde054cd376e144fcae8"
  secret_key_base: f3cd38b3e7ea807c40b01cf0d5546176c463777a3351903b1688631c0da63e60cb2720daa7fc323d4696fcdeaa05e40b7fb9fbab2bc6c93dfdaa8c6cba4dcd87
  mailgun_api_key: key-4d89c843537d5769b4ffebbc4bad4593
  mailgun_mailing_list: "newsletter@mailgun.eebulle.ch"
  uploader_provider: "Google"
  google_storage_access_key_id: "GOOG65JNHDRFZTF7GN47"
  google_storage_secret_access_key: "7BlkrSTcg+L0fV4y02MD9FDRi7CG4UTl/t08MgQE"
  passwords:
    worship: "plantes"
    leaders: "superhero"
    messages: "pizza"
