local:
  service: Disk
  root: <%= Rails.root.join("public/uploads") %>

google:
  service: GCS
  credentials: <%= Rails.root.join("config/gcs.json") %>
  project: "bulle-network"
  bucket: "eebulle-ch"
